-- Run this script in Supabase SQL Editor.
-- It creates the livestock table and configures public read/insert access.

create table if not exists public.livestock (
  id bigint generated by default as identity primary key,
  name text not null check (char_length(name) >= 2),
  breed text not null check (char_length(breed) >= 2),
  price_ksh numeric(12,2) not null check (price_ksh >= 0),
  health_status text not null default 'Healthy',
  image_url text,
  created_at timestamptz not null default now()
);

alter table public.livestock
  add column if not exists price_ksh numeric(12,2);
do $$
begin
  if exists (
    select 1
    from information_schema.columns
    where table_schema = 'public'
      and table_name = 'livestock'
      and column_name = 'price'
  ) then
    execute '
      update public.livestock
      set price_ksh = price
      where price_ksh is null and price is not null
    ';
  end if;
end $$;
alter table public.livestock
  alter column price_ksh set not null;

alter table public.livestock
  add column if not exists health_status text not null default 'Healthy';
alter table public.livestock
  add column if not exists image_url text;
alter table public.livestock
  add column if not exists weight numeric(8,2);
alter table public.livestock
  add column if not exists age numeric(5,1);
alter table public.livestock
  add column if not exists status text default 'Active' check (status in ('Active', 'For Sale', 'Sold', 'Retired'));
alter table public.livestock
  add column if not exists sale_price numeric(12,2) check (sale_price >= 0);

create index if not exists livestock_created_at_idx
  on public.livestock (created_at desc);

alter table public.livestock enable row level security;

drop policy if exists "Public read livestock" on public.livestock;
create policy "Public read livestock"
  on public.livestock
  for select
  to anon, authenticated
  using (true);

drop policy if exists "Public insert livestock" on public.livestock;
create policy "Public insert livestock"
  on public.livestock
  for insert
  to anon, authenticated
  with check (true);

drop policy if exists "Authenticated update livestock" on public.livestock;
create policy "Authenticated update livestock"
  on public.livestock
  for update
  to authenticated
  using (true)
  with check (true);

drop policy if exists "Authenticated delete livestock" on public.livestock;
create policy "Authenticated delete livestock"
  on public.livestock
  for delete
  to authenticated
  using (true);

-- Storage bucket for livestock photos
insert into storage.buckets (id, name, public)
values ('cow photos', 'cow photos', true)
on conflict (id) do nothing;

drop policy if exists "Public read livestock photos" on storage.objects;
create policy "Public read livestock photos"
  on storage.objects
  for select
  to anon, authenticated
  using (bucket_id = 'cow photos');

drop policy if exists "Public upload livestock photos" on storage.objects;
create policy "Public upload livestock photos"
  on storage.objects
  for insert
  to anon, authenticated
  with check (bucket_id = 'cow photos');

drop policy if exists "Authenticated update livestock photos" on storage.objects;
create policy "Authenticated update livestock photos"
  on storage.objects
  for update
  to authenticated
  using (bucket_id = 'cow photos')
  with check (bucket_id = 'cow photos');

drop policy if exists "Authenticated delete livestock photos" on storage.objects;
create policy "Authenticated delete livestock photos"
  on storage.objects
  for delete
  to authenticated
  using (bucket_id = 'cow photos');

-- Health logs table for tracking livestock health conditions and treatments
create table if not exists public.health_logs (
  id bigint generated by default as identity primary key,
  livestock_id bigint not null references public.livestock(id),
  condition text not null,
  treatment text,
  cost numeric(10,2) default 0 check (cost >= 0),
  created_at timestamptz not null default now()
);

create index if not exists health_logs_created_at_idx
  on public.health_logs (created_at desc);

create index if not exists health_logs_livestock_id_idx
  on public.health_logs (livestock_id);

alter table public.health_logs enable row level security;

drop policy if exists "Public read health_logs" on public.health_logs;
create policy "Public read health_logs"
  on public.health_logs
  for select
  to anon, authenticated
  using (true);

drop policy if exists "Public insert health_logs" on public.health_logs;
create policy "Public insert health_logs"
  on public.health_logs
  for insert
  to anon, authenticated
  with check (true);

-- Production logs table for milk production tracking
create table if not exists public.production_logs (
  id bigint generated by default as identity primary key,
  livestock_id bigint not null references public.livestock(id),
  litres numeric(10,2) not null check (litres >= 0),
  milk_kg numeric(10,2) not null check (milk_kg >= 0),
  created_at timestamptz not null default now()
);

create index if not exists production_logs_created_at_idx
  on public.production_logs (created_at desc);

create index if not exists production_logs_livestock_id_idx
  on public.production_logs (livestock_id);

alter table public.production_logs enable row level security;

drop policy if exists "Public read production_logs" on public.production_logs;
create policy "Public read production_logs"
  on public.production_logs
  for select
  to anon, authenticated
  using (true);

drop policy if exists "Public insert production_logs" on public.production_logs;
create policy "Public insert production_logs"
  on public.production_logs
  for insert
  to anon, authenticated
  with check (true);

-- Expenses table for tracking farm costs
create table if not exists public.expenses (
  id bigint generated by default as identity primary key,
  category text not null check (category in ('Feed', 'Vet', 'Worker', 'AI')),
  amount numeric(10,2) not null check (amount >= 0),
  expensed_date date not null,
  created_at timestamptz not null default now()
);

create index if not exists expenses_created_at_idx
  on public.expenses (created_at desc);

create index if not exists expenses_expensed_date_idx
  on public.expenses (expensed_date desc);

alter table public.expenses enable row level security;

drop policy if exists "Public read expenses" on public.expenses;
create policy "Public read expenses"
  on public.expenses
  for select
  to anon, authenticated
  using (true);

drop policy if exists "Public insert expenses" on public.expenses;
create policy "Public insert expenses"
  on public.expenses
  for insert
  to anon, authenticated
  with check (true);
